#' If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.Find the sum of all the multiples of 3 or 5 below 1000.
q1_naive <- function() {
  N = 1000
  to_send <- 0
  for (i in 1:(N-1)) {
    div_5 <- i %% 5 == 0
    div_3 <- i %% 3 == 0
    if (div_3 || div_5) to_send = to_send + i
  }
  to_send
}

q1_better <- function() {
  N <- 1000
  to_send <- 0
  div_3 <- 3*floor(999/3)*(floor(999/3)+1)/2
  div_5 <- 5*floor(999/5)*(floor(999/5)+1)/2
  div_15 <- 15*floor(999/15)*(floor(999/15)+1)/2
  div_3 + div_5 - div_15
}


#'Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#' 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#' By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
q2_naive <- function() {
  N = 4000000 #4Million
  # N <- 100
  prev <- 1
  prev_prev <- 0
  to_send <- 0
  while (TRUE) {
    next_ = prev + prev_prev
    if (next_ > N) break
    if (next_ %% 2 == 0)
      to_send <- to_send + next_
    prev_prev <- prev
    prev <- next_
  }
  to_send
}


#' The prime factors of 13195 are 5, 7, 13 and 29.
#' What is the largest prime factor of the number 600851475143 ?

q3_naive <- function() {
  N <- 600851475143
  max_prime <- function(N){
    p <- 2
    to_send <- c()
    while (N > 1) {
      while (N %% p == 0) {
        to_send <- c(to_send, p)
        N <- N/p
      } p <- p +1
    }
    tail(to_send, 1)
  }
  max_prime(N)
}

